"""商品完整名称与 SAM3 prompt 的一一对应表。"""


PROMPT_MAPPING: dict[str, str] = {
    "NFC桔汁": "juice carton",
    "蒙牛纯牛奶": "milk carton",
    "纯甄酸奶": "yogurt carton",
    "百草味海苔肉松蛋卷": "packaged product",
    "三只松鼠每日坚果": "packaged product",
    "费列罗巧克力": "packaged product",
    "双汇王中王火腿肠": "packaged product",
    "妙芙香芋牛奶味": "packaged product",
    "妙芙绵醇奶油味": "packaged product",
    "妙芙巧克力味": "packaged product",
    "薯愿非油炸清新番茄味": "potato chip can",
    "薯愿非油炸韩国泡菜味": "potato chip can",
    "薯愿非油炸香烤原味": "potato chip can",
    "品客薯片烧烤牛排味": "potato chip can",
    "品客原味": "potato chip can",
    "品客酸乳酪洋葱味": "potato chip can",
    "奥利奥香甜不腻": "packaged product",
    "奥利奥冰淇淋抹茶味": "packaged product",
    "奥利奥浓醇巧克力味": "packaged product",
    "奥利奥白桃乌龙味": "packaged product",
    "Lays乐事薯片墨西哥鸡汁番茄味": "packaged product",
    "Lays乐事薯片经典原味": "packaged product",
    "Lays乐事薯片黄瓜味": "packaged product",
    "Lays乐事薯片意大利香浓红烩味": "packaged product",
    "Lays乐事薯片青柠味": "packaged product",
    "呀！土豆番茄酱味": "packaged product",
    "好友趣韩国泡菜味": "packaged product",
    "卫龙辣条": "packaged product",
    "百醇草莓香草味": "packaged product",
    "百醇巧克力味": "packaged product",
    "上好佳鲜虾条": "packaged product",
    "浪味仙": "packaged product",
    "好丽友派": "packaged product",
    "吐司方方原味": "packaged product",
    "好友趣蜂蜜黄油味": "packaged product",
    "可孚棉签": "personal care package",
    "小鹿妈妈牙线": "personal care package",
    "得宝纸巾": "tissue package",
    "草原红太阳烧烤料原味": "condiment package",
    "草原红太阳烧烤料香辣味": "condiment package",
    "草原红太阳烧烤酱香辣": "condiment package",
    "草原红太阳烧烤酱原味": "condiment package",
    "海氏海诺创口贴": "personal care package",
    "德佑湿巾": "tissue package",
    "心相印纸巾": "tissue package",
    "合味道海鲜味": "instant noodle cup",
    "合味道五香牛肉味": "instant noodle cup",
    "农心碗面": "instant noodle cup",
    "健食力低脂香肠": "packaged product",
    "妙洁海绵百洁布": "packaged product",
    "康师傅香辣牛肉面": "instant noodle cup",
    "康师傅鲜虾鱼板面": "instant noodle cup",
    "康师傅老坛酸菜牛肉面": "instant noodle cup",
    "好人家火锅底料": "condiment package",
    "纯棉酒店大毛巾": "towel",
    "京东京造毛巾": "towel",
    "三色藜麦": "food bag",
    "慢碳十色糙米": "food bag",
    "高纤七色糙米": "food bag",
    "山西黄小米": "food bag",
    "界面医疗医用外科口罩": "face mask package",
    "中盐精制盐": "food bag",
    "小苏打": "food bag",
    "镇江香醋": "condiment bottle",
    "蒸鱼豉油": "condiment bottle",
    "薄盐生抽": "condiment bottle",
    "可口可乐罐装": "beverage can",
    "雪碧罐装": "beverage can",
    "芬达罐装": "beverage can",
    "百事可乐瓶装": "beverage bottle",
    "7喜瓶装": "beverage bottle",
    "水溶C100瓶装": "beverage bottle",
    "小青柠汁饮料": "beverage bottle",
    "美年达瓶装": "beverage bottle",
    "名仁苏打水饮料": "beverage bottle",
    "东方树叶茉莉花茶": "beverage bottle",
    "绿豆冰沙": "beverage bottle",
    "外星人电解质水椰子口味": "beverage bottle",
    "外星人电解质水青柠口味": "beverage bottle",
    "外星人电解质水白桃口味0糖": "beverage bottle",
    "外星人电解质水西柚口味": "beverage bottle",
    "尖叫": "beverage bottle",
    "百岁山矿泉水": "beverage bottle",
    "脉动观梅止渴饮": "beverage bottle",
    "脉动芒果口味": "beverage bottle",
    "脉动菠萝口味": "beverage bottle",
    "脉动猫薄荷瓶": "beverage bottle",
    "外星人电解质水青柠口味0糖": "beverage bottle",
    "宝矿力水特": "beverage bottle",
    "舒肤佳香皂纯白清香型": "soap bar",
    "舒肤佳香皂芦荟呵护香型": "soap bar",
    "舒肤佳香皂柠檬清新香型": "soap bar",
    "汰渍肥皂": "soap bar",
    "杯子": "cup",
    "舒克牙膏竹炭薄荷": "toothpaste tube",
    "舒克牙膏柠檬百香果": "toothpaste tube",
    "舒克牙膏海盐薄荷": "toothpaste tube",
    "冷酸灵云感觉牙刷": "toothbrush package",
    "Dove沐浴泡泡樱花甜香": "personal care bottle",
    "Dove沐浴泡泡白桃果香": "personal care bottle",
    "Dove沐浴泡泡清甜奶香": "personal care bottle",
    "威露士": "personal care bottle",
    "Dove沐浴乳": "personal care bottle",
    "拖鞋": "slippers",
    "Dove沐浴泡泡樱花甜香袋装": "refill pouch",
    "半亩花田洗发水": "personal care bottle",
    "心相印厨房纸巾": "paper towel roll",
}


def get_sam3_prompt(name: str) -> str:
    if not name in PROMPTS:
        return False
    return PROMPT_MAPPING[name]
